export const SITE = {
  name: 'Naresh Basude',
  domain: 'nareshbasude.in',
  url: 'https://nareshbasude.in',
  title: 'Website & App Developer in Thane · Naresh Basude',
  description:
    'Website & app developer in Thane. Naresh Basude builds sites, web apps, mobile apps, WhatsApp bots & runs Meta/Google ads for SMBs across Mumbai and India.',
  tagline: 'I ship the site, run the campaign, and design the whole funnel.',
  email: 'nareshbasude9@gmail.com',
  locale: 'en_IN',
  language: 'en',
  country: 'IN',
  region: 'MH',
  city: 'Thane',
  fullAddress: {
    locality: 'Thane',
    region: 'Maharashtra',
    country: 'India',
    postalCode: '400601',
  },
  areaServed: [
    'Thane',
    'Mumbai',
    'Navi Mumbai',
    'Kalyan',
    'Bhiwandi',
    'Dombivli',
    'Mira-Bhayandar',
    'Mira Road',
    'Bhayandar',
    'Vasai',
    'Virar',
    'Nalasopara',
    'Panvel',
    'Kalamboli',
    'Kamothe',
    'Ulwe',
    'Ulhasnagar',
    'Ambernath',
    'Badlapur',
    'India',
    'Remote worldwide',
  ],
  themeColor: '#050505',
  ogImage: '/og.png',
  twitterHandle: '',
  jobTitle: 'Website Developer, App Developer, Digital Marketer & Designer',
  knowsAbout: [
    'Website Development',
    'App Development',
    'Next.js',
    'React',
    'Astro',
    'TypeScript',
    'Node.js',
    'WordPress Development',
    'WhatsApp Chatbots',
    'Headless E-commerce',
    'Lead Management Systems',
    'SEO',
    'Generative Engine Optimization',
    'Growth Marketing',
    'Meta Ads',
    'Google Ads',
    'Brand Identity',
    'UI Design',
    'Conversion Rate Optimization',
    'Local SEO Thane',
    'Local SEO Bhiwandi',
    'Local SEO Mumbai',
  ],
  availability: 'Available now',
} as const;

export const NAV = [
  { num: '01', label: 'Work', href: '/projects' },
  { num: '02', label: 'Writing', href: '/writing' },
  { num: '03', label: 'About', href: '/about' },
  { num: '04', label: 'Contact', href: '/contact' },
] as const;

export const CONTACT = {
  phone: '+918600574836',
  phoneDisplay: '+91 86005 74836',
  whatsapp: '918600574836', // digits only, no + or spaces — for wa.me link
  linkedin: 'https://in.linkedin.com/in/website-developer-in-thane',
  github: '', // optional — to be filled later
  twitter: '', // optional — to be filled later
} as const;
